services:
  php:
    image: tugboatqa/php:8.1-apache
    default: true
    depends: mysql
    commands:
      init:
        - apt-get update
        - apt-get install -y libzip-dev
        - docker-php-ext-install mysqli zip
        - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        - chmod +x wp-cli.phar
        - mv wp-cli.phar /usr/local/bin/wp
      update:
        - ln -snf "${TUGBOAT_ROOT}/web" "${DOCROOT}"
        - mkdir -p "${DOCROOT}/wp-content/uploads" || /bin/true
        - chgrp -R www-data "${DOCROOT}/wp-content/uploads"
        - find "${DOCROOT}/wp-content/uploads" -type d -exec chmod 2775 {} \;
        - find "${DOCROOT}/wp-content/uploads" -type f -exec chmod 0664 {} \;

  mysql:
    image: tugboatqa/mysql:8-debian
